name: Build Avalanche Reports
on:
  # Run at 06:33 and 18:33 PT daily
  schedule:
    - cron: '03 02,14 * * *'
    - cron: '33 01,14 * * *'
  # (optional) Run workflow manually
  workflow_dispatch:
jobs: 
  avalanche:
    name: Build Avlanche data
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Run python scripts
      run: |
        set -xe
        python -VV
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python tools/avy/download-avy-json.py
        python tools/avy/caltopo-layers.py
        python tools/avy/avalanche.py

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Update built avalanche data"
        add: '["source/assets/json/avalanche-reports", "source/avy", "source/assets/json/avalanche-zones", "source/assets/images/svg/avalanche-zones"]' 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
