name: Build Avalanche Reports
on:
  # Run at 06:33 and 18:33 PT daily
  schedule: [{cron: "33 2,14 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs: 
  avalanche:
    name: Build Avlanche data
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Run script
      run: |
        set -xe
        python -VV
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python download-avy-json.py
        python caltopo-layers.py
        python avalanche.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Update built avalanche data"
        add: "source/assets/json/avalanche-reports"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
